### PR TITLE
Initial SDK docs and tutorial

### PR DESCRIPTION
**Pull request by sinnec**

### CODE REVIEW

**Review by NickNtamp — APPROVED** [review]
To be honest I found it great! Amazing job @sinnec.
I liked also the colors, fonts, styles etc.
I am not agree with the structure of contents as it confuses me a lot but it is not something up to you.
Once again, great work!

**Review by momegas — APPROVED** [review]

**Comment by stavrostheocharis** [comment]
Guys why did we merge this with pending review comments?

**Comment by sinnec** [comment]
Well it was approved by two people! Plus the structure of the docs is tracked in #62

**Comment by stavrostheocharis** [comment]
Ok,  it is not an issue for now since these were minor changes, but it is good in general to solve all the pending parts before merging :)

**Pull request merged**
